spring:
  datasource:
    url: jdbc:p6spy:h2:mem:testdb
    username: sa
    password: 123
    #driver-class-name: org.h2.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  h2:
    console:
      enabled: true      settings:        web-allow-others: true
  batch:
    jdbc:      initialize-schema: always
    job:      enabled: true 
  jpa:
    show-sql: false    hibernate:
      ddl-auto: create
logging:  level:    root: info
      